import { Header } from '@/components/elements/Header'
import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import './globals.css'

const poppins = Poppins({
	variable: '--font-poppins',
	subsets: ['latin'],
	weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
})

export const metadata: Metadata = {
	title: 'PGS Admin Panel',
	description: 'Generated by create next app',
	icons: {
		icon: '/logo.png'
	}
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={`${poppins.variable} antialiased`}>
				<Header />
				<main>{children}</main>
			</body>
		</html>
	)
}
