import { Header } from '@/components/elements/Header'
import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import './globals.css'

const poppins = Poppins({
	variable: '--font-poppins',
	subsets: ['latin'],
	weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
})

export const metadata: Metadata = {
	title: 'PGS Admin Panel',
	description: 'Generated by create next app',
	icons: {
		icon: '/logo.png'
	}
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body
				className={`${poppins.variable} antialiased min-w-screen min-h-screen overflow-x-hidden`}
			>
				<Header />
				<main className='w-full h-full flex place-content-center'>
					<div className='w-3/4 max-lg:w-9/10 flex justify-center bg-white p-5 rounded-xl mt-5'>
						{children}
					</div>
				</main>
			</body>
		</html>
	)
}
